import type { NextPage } from 'next'
import Head from 'next/head'
import Sidenav from 'components/Sidenav'
import Profile from 'components/Profile'
import Results from 'components/Results'
import TimeStats from 'components/TimeStats'
import WelcomeBanner from 'components/WelcomeBanner'
import Image from 'next/image'
import SearchIcon from 'assets/icons/search-icon.svg'
import Courses from 'components/Courses'

const Home: NextPage = () => {
  return (
    <div className='grid grid-cols-[321px_auto_487px]'>
      <Head>
        <title>Socket Charge Assignment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Sidenav />
      <div></div>
      <main className='px-[51px] py-[57px] max-w-[1200px]'>
        <div className='flex justify-end'>
          <div className='flex items-center gap-[25px] mb-[59px]'>
            <p>22 Feb 2022</p>
            <div className='w-[53px] h-[54px] bg-[#E5E9FA] rounded-[12px] flex items-center justify-center'>
              <Image src={SearchIcon} width={18} height={18} alt='search' />
            </div>
          </div>
        </div>
        <WelcomeBanner />
        <section className='mt-[40px] flex gap-[32px]'>
          <Results />
          <TimeStats />
        </section>
        <Courses />
      </main>
      <Profile />
    </div>
  )
}

export default Home
